"""add invoice payment amounts

Revision ID: 075c12467686
Revises: 45778f4ac547
Create Date: 2026-09-04 02:42:08.335371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075c12467686'
down_revision: Union[str, Sequence[str], None] = '45778f4ac547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('normalized_events', sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('normalized_events', sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('normalized_events', 'amount_due')
    op.drop_column('normalized_events', 'amount_paid')
    # ### end Alembic commands ###
