"""add recovery escalations

Revision ID: 540169978698
Revises: 41d1b9dc4c6a
Create Date: 2026-09-04 16:36:12.475774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540169978698'
down_revision: Union[str, Sequence[str], None] = '41d1b9dc4c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_recovery_attempts_case_id'), 'recovery_attempts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_recovery_attempts_case_id'), 'recovery_attempts', 'recovery_cases', ['case_id'], ['case_id'])
    # ### end Alembic commands ###
