"""add revenue object ids to recovery attempts

Revision ID: 7133ca3a7956
Revises: f7b5e12f83be
Create Date: 2026-09-03 21:55:29.191311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7133ca3a7956'
down_revision: Union[str, Sequence[str], None] = 'f7b5e12f83be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_attempts', sa.Column('subscription_id', sa.String(length=255), nullable=True))
    op.add_column('recovery_attempts', sa.Column('invoice_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_recovery_attempts_invoice_id'), 'recovery_attempts', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_recovery_attempts_subscription_id'), 'recovery_attempts', ['subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_recovery_attempts_subscription_id'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_invoice_id'), table_name='recovery_attempts')
    op.drop_column('recovery_attempts', 'invoice_id')
    op.drop_column('recovery_attempts', 'subscription_id')
    # ### end Alembic commands ###
